### ISSUE TITLE
Add entity for toggle switch

### ISSUE THREAD

**Issue by Nivlac7** [chemelli74/aiocomelit#103]
Hello!

I am happy user of your comelit core integration in Home Assistant, thanks a lot for this, it’s working great!

I do believe it would be a great feature to have all toggle switches exposed as entity in HA so that we could use those as input for other HA integration. Maybe not possible due to the serial bridge way of working, not sure about this? 

Thanks whatsoever for your work and support!

**Comment by chemelli74** [comment]
Hi @Nivlac7, thank you for your feedback.

I'm not sure which switch you are looking for.
Can you please detail your needs so we can check if it's feasible ?

**Comment by Nivlac7** [comment]
I am referring about all the input on the comelit modules.

e.g. for a SIMPLEHOME MODULE 9 IN/8 OUT you have the output exposed already (lights usually) but not the 8 input (which are usually set to trigger the output)

Module used in my example: https://pro.comelitgroup.com/en-gb/product/20046605

**Comment by chemelli74** [comment]
You mean that you miss output for switches not configured as light ?
If so, what are those used for ? Sockets ?

**Comment by Nivlac7** [comment]
No, sockets are very well exposed :) 

I meant the push buttons (2 wires making the contact to on/off lights) going into input of modules… but that’s not part of what the comelit serial bridge shows as such so I believe you don’t have access to it?

**Comment by chemelli74** [comment]
Please join HomeAssistant  on [Discord](https://discord.com/invite/home-assistant) and then contact me: `chemelli74#2180` so we can go in depth

**Comment by chemelli74** [comment]
Closing for missing feedback

**Comment by Nivlac7** [comment]
Sorry for no feed-back, I tried to define some input switch within the comelit software but it turned out to be not possible with the Serial BUS. Therefore my request does not make sense.
