### ISSUE TITLE
How to Install Comelit Integration on HA

### ISSUE THREAD

**Issue by Marcoletto** [chemelli74/aiocomelit#109]
Ciao Simone,
non riesco a trovare un modo per installare l' integrazione Comelit per poter leggere e comandare il mio allarme Comelit vedo tramite la scheda VedoIP.

Mi potresti aiutare?

Grazie 1000,
Marco

**Comment by DarkanParx** [comment]
In che senso? Una volta installata l'integrazione devi configurarla inserendo l'ip locale del tuo Vedo e il tuo pin, e selezionare Vedo nel box inferiore

**Comment by Marcoletto** [comment]
> In che senso? Una volta installata l'integrazione devi configurarla inserendo l'ip locale del tuo Vedo e il tuo pin, e selezionare Vedo nel box inferiore

Nel senso che non so come installare l' integrazione.
Però forse questaintegrazione non funziona in Home Assistant?

**Comment by DarkanParx** [comment]
L'integrazione è parte del core di Home assistant, la installi come qualsiasi altra integrazione. Basta cliccare su Nuova integrazione e cercare Comelit

**Comment by Marcoletto** [comment]
Grazie,
non me la trovava; presumo perchè avevo installato un' altra integrazione Comelit (che non funzionava) e mi andava in conflitto non trovando quella corretta.

Grazie!
