### ISSUE TITLE
Numeric PIN containing 0 at the beginning

### ISSUE THREAD

**Issue by emabiz** [chemelli74/aiocomelit#173]
Hi,
thank you for your work.

I tried the integration and I notice that the pin is numeric, but doen't accept the digit 0 at the beginning, because they are automatically trimmed out.

So if you have a pin that starts with 0 you cannot authenticate

**Comment by chemelli74** [comment]
Thx for reporting, will take a look hopefully tomorrow

**Comment by chemelli74** [comment]
Can you please try using `library_test.py` from this repo ?

If you need help, please join HomeAssistant  on [Discord](https://discord.com/invite/home-assistant) and then contact me: `chemelli74#2180`

**Comment by emabiz** [comment]
I will do it for sure asap.
But in library_test.py you accept  the pin as string, then I expect that it will work.
In the configuration card inside HA the field is numeric

**Comment by chemelli74** [comment]
> I will do it for sure asap. But in library_test.py you accept the pin as string, then I expect that it will work. In the configuration card inside HA the field is numeric

Once we are sure that it works on library side, you should then open an issue on HA side.
I bet more for the Alarm card than for Comelit integration itself.

**Comment by emabiz** [comment]
ah, that's why I don't find anything related to HA config in this repo.
I am not an expert of HA and I thought that the config ui for an integration must be provided by the integration itself.
But actually I don't see any code related to this in your project

**Comment by emabiz** [comment]
Hi, I made a quick test.
To make it work I had to add a sleep after the cookie reception (just before the final check_logged_in), otherwise I get zero in domus and it cannot login.
![image](https://github.com/user-attachments/assets/ff936f3c-0c4e-4c06-aae9-19a5e5123f0b)
I put 1 sec just to be sure to wait enough.

I could go deeper in debug here to understand the reason, when I have more time available.

Also I had to change the check of existence of config file
`os.path.exists(arguments.configfile):#Path.exists(arguments.configfile):`

otherwise I get the exception:
![image](https://github.com/user-attachments/assets/fb431edc-3b00-4249-b692-337250b36b04)

With these 2 modifications it works fine and I can see comelit status. 


If I enable VEDO alarm I get the following error (also here I can debug more, if necessary)
![image](https://github.com/user-attachments/assets/81f1116d-901b-46c3-b6dc-34d65aa67411)

My question is how guys from home assistant know which UI is needed to configure your integration? I expect that is the integration itself that contains the UI or the config to build it

**Comment by emabiz** [comment]
I think the problem is here for the conf:
` vol.Optional(CONF_PIN, default=DEFAULT_PIN): cv.positive_int,`
it should be a string and not a positive int.
![image](https://github.com/user-attachments/assets/947a0373-3284-47de-a5cb-d158f3ccce6b)

**Comment by emabiz** [comment]
...and when I exit home I found one irrigator on  :)

**Comment by chemelli74** [comment]
> Hi, I made a quick test. 
>To make it work I had to add a sleep after the cookie reception
> [...]
> Also I had to change the check of existence of config file 
> [...]
> If I enable VEDO alarm I get the following error 

Making a fully working development env is not always so easy.
I would suggest you go with the `devcontainer`, part of this repo, that will do all the setup for you.

**Comment by chemelli74** [comment]
> I think the problem is here for the conf: 
> ` vol.Optional(CONF_PIN, default=DEFAULT_PIN): cv.positive_int,`
> it should be a string and not a positive int. 

This is a issue in the HA integration, not in this repo code.
Please report in the right place.
