### ISSUE TITLE
Long delay to update state

### ISSUE THREAD

**Issue by Nivlac7** [chemelli74/aiocomelit#180]
**Describe the bug**
When button (i.e. light switch) pressed, it takes a couple of second to update the state. If I press it a second time rapidly, it can take up to 10 second to have the state correctly updated on the dash board.

**To Reproduce**
Steps to reproduce the behavior: Press twice a light button on HA dashboard in a short interval.

**Additional context**
- I expose all those entities to homekit with homekit bridge and within homkit, everything is immediate.
- I don't have same issues with other entities on my HA dashboard (e.g. zigbee with z2m)
- Problem (i.e. delay) seems to get worst over time

**Comment by chemelli74** [comment]
Please enable [debug](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging) for **Comelit Simplehome** integration, wait for this error, disable debug and attach the log.

Note: it is better to drag the log into the comment (which will add it as an attachment) and not copy paste as it is hard to read logs in GitHub.

Thanks

**Comment by Nivlac7** [comment]
Hello,

I activated the recording and made a couple of actions which immediately triggered the "long delay" and stopped recording.

I hope it helps finding the issue :)

Thanks!

[home-assistant_2024-10-20T13-25-35.468Z.log](https://github.com/user-attachments/files/17450388/home-assistant_2024-10-20T13-25-35.468Z.log)

**Comment by chemelli74** [comment]
Please tell me the light you switched on so it's easier to identify them in the log.

**Comment by Nivlac7** [comment]
I Think it was « boules Salon »
I will redo it if needed 😅

**Comment by Nivlac7** [comment]
New logs, made it 3 times on "Boules Salon" On & Off rapidly and it took 5-6 seconds to update the status to off each time.

[home-assistant_comelit_2024-10-24T07-34-17.831Z.log](https://github.com/user-attachments/files/17502986/home-assistant_comelit_2024-10-24T07-34-17.831Z.log)

**Comment by chemelli74** [comment]
> New logs, made it 3 times on "Boules Salon" On & Off rapidly and it took 5-6 seconds to update the status to off each time.
> 
> [home-assistant_comelit_2024-10-24T07-34-17.831Z.log](https://github.com/user-attachments/files/17502986/home-assistant_comelit_2024-10-24T07-34-17.831Z.log)

`aiocomelit` is based on a pull request, as there is no push notification from bridge.
HomeAsisstant allows a refresh rate as short as 5s.

So depending on where the interval between the two refresh is, the worst scenario is 5s.
It may also happen to be shorter, but never longer nor immediate.

**Comment by Nivlac7** [comment]
Thanks for the answer, indeed 5 seconds seems to be the "normal" delay when there are 2 consecutive requests...
Just asking, is it not possible to simply pull the state as soon as a service is called? e.g. light.Toggle initiate a sepcefic pull request regardless of the interval?

For my understanding,  what could be the reason homekit (using homekit bridge with your integration) is behaving differently? With homekit, the state update is always immediate and every request is sent correctly while with HA board, when in the 5s interval, the request are not even going through (i.e. making quick on/off)?

Sorry if I bother you going too far in my expectations :)

**Comment by chemelli74** [comment]
Please join HomeAssistant  on [Discord](https://discord.com/invite/home-assistant) and then contact me: `chemelli74#2180`

Simone
