### ISSUE TITLE
Comelit MINI HANDSFREE WIFI (6741W)

### ISSUE THREAD

**Issue by MicheleMercuri** [chemelli74/aiocomelit#40]
Hi, can you add to your integration support for Comelit MINI HANDSFREE WIFI (6741W).
HANDSFREE WIFI (6741W) has a server on ip:8080 and a TCP/UDP local port on 64100.
Many thanks,
Regards.

**Comment by serot23** [comment]
@chemelli74 hi it functions are as followed: video calling, mute/ unmute, physical ring volume switch(3 steps) , 2 pot meters 1x contrast and 1x talk volume. Turn on screen by pressing number 2 without someone ringing. Button 1 doesn't have a real function, only for programming a ring sound. There is also a missed call button, like a envelop icon and a menu button. Inside the menu there are several options, like connecting to wifi, testing connection and some other simple stuff. There is also a facial recognition function in the app.

**Comment by MicheleMercuri** [comment]
> chemelli74#2180

I think it's same a comelit smathome server: https://pro.comelitgroup.com/it-it/prodotto/6741w

by now i can open gate using nodered:

https://community.home-assistant.io/t/comelit-video-intercom/15128/19

**Comment by chemelli74** [comment]
Need to understand if it's based on [web scraping](https://it.wikipedia.org/wiki/Web_scraping) or native [json](https://www.json.org/json-en.html) (as Brige and VEDO).

**Comment by serot23** [comment]
https://dev1.cloud.comelitgroup.com/

Here it states it uses json for google services, but i don't know what the differences are between webscraping and json, i have read it but don't really understand it

**Comment by chemelli74** [comment]
I think this project is the more up-to-date: <https://github.com/mansellrace/comelit-esphome>

If someone of you try it out. please update this issue with the results.

**Comment by chemelli74** [comment]
Please follow above suggestion, closing.
